version: '3.4'

services:
    goestools:
        image: 192.168.1.3:5000/hemna/goestools
        container_name: goestools
        user: 1000:1000
        hostname: goestools
        restart: unless-stopped
        volumes:
            - /opt/docker/goestools/data:/home/goes/data
