version: '3.4'

services:
    goestools:
        image: harbor.hemna.com/hemna6969/goestools
        container_name: goestools
        user: 1000:1000
        hostname: goestools
        restart: unless-stopped
        volumes:
            - /opt/docker/goestools/data:/home/goes/data
        networks:
            - goestools_net

networks:
    goestools_net:

