---
resource_types:
    - name: docker-compose
      type: docker-image
      source:
          repository: troykinsella/concourse-docker-compose-resource
          tag: latest

    - name: slack-alert
      type: docker-image
      source:
        repository: arbourd/concourse-slack-alert-resource

resources:
  - name: goestools-src
    type: git
    source:
      uri: https://github.com/pietern/goestools

  - name: docker-goestools-src
    type: git
    source:
      uri: https://github.com/hemna/docker-goestools

  - name: goestools-docker-image
    type: docker-image
    source:
        repository: 192.168.1.3:5000/hemna/goestools
        username: ((private-reg-user))
        password: ((private-reg-password))
        tag: latest
        debug: true
        insecure_registries: [ "192.168.1.3:5000" ]

  - name: docker-compose
    type: docker-compose
    source:
        host: 192.168.1.44

  - name: slack-notify
    type: slack-alert
    source:
        url: https://hooks.slack.com/services/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


jobs:
  - name: README
    serial: true
    plan:
    - task: describe-this-pipeline
      config:
        platform: 'linux'
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: latest
        run:
          path: /bin/echo
          args:
          - -e
          - '\t    This pipeline is defined at: https://github.com/hemna/docker-goestools/tree/master/ci\n'

  - name: build-and-publish-goestools
    public: true
    serial: true
    plan:
      - do:
        - get: goestools-src
          trigger: true
        - get: docker-goestools-src
          trigger: true
        - put: goestools-docker-image
          params: 
            build: docker-goestools-src/build/
    on_failure:
        try:
            put: slack-notify
            params:
              alert_type: failed
    on_success:
        try:
            put: slack-notify
            params:
              alert_type: success


  - name: restart-container
    public: true
    serial: true
    plan:
      - get: docker-goestools-src
        trigger: true
        passed: [build-and-publish-goestools]
      - put: docker-compose
        params:
            command: down
            compose_file: docker-goestools-src/docker/docker-compose.yml
      - put: docker-compose
        params:
            command: up
            compose_file: docker-goestools-src/docker/docker-compose.yml

    on_failure:
        try:
            put: slack-notify
            params:
              alert_type: failed

    on_success:
        try:
            put: slack-notify
            params:
              alert_type: success
