---
resource_types:
    - name: hangouts-resource
      type: docker-image
      source:
          repository: cloudinn/concourse-hangouts-resource
          tag: latest
          post_url: true

    - name: docker-compose
      type: docker-image
      source:
          repository: troykinsella/concourse-docker-compose-resource
          tag: latest

resources:
  - name: goestools-src
    type: git
    source:
      uri: https://github.com/pietern/goestools

  - name: docker-goestools-src
    type: git
    source:
      uri: https://github.com/hemna/docker-goestools

  - name: goestools-docker-image
    type: docker-image
    source:
        repository: 192.168.1.3:5000/hemna/goestools
        username: ((private-reg-user))
        password: ((private-reg-password))
        tag: latest
        debug: true
        insecure_registries: [ "192.168.1.3:5000" ]

  - name: docker-compose
    type: docker-compose
    source:
        host: 192.168.1.44

  - name: hangouts-chat
    type: hangouts-resource
    source:
        webhook_url: ((hangouts-chat-webhook-url))
        post_url: true

jobs:
  - name: README
    serial: true
    plan:
    - task: describe-this-pipeline
      config:
        platform: 'linux'
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: latest
        run:
          path: /bin/echo
          args:
          - -e
          - '\t    This pipeline is defined at: https://github.com/hemna/docker-goestools/tree/master/ci\n'

  - name: build-and-publish-goestools
    public: true
    serial: true
    plan:
      - do:
        - get: goestools-src
          trigger: true
        - get: docker-goestools-src
          trigger: true
        - put: goestools-docker-image
          params: 
            build: docker-goestools-src/build/
    on_failure:
        try:
            put: hangouts-chat
            params:
                message: Building the latest goestools docker image FUCKING FAILED BITCH!  HAHAHAH!!
    on_success:
        try:
            put: hangouts-chat
            params:
                message: New goestools image up bitch!
                post_url: false


  - name: restart-container
    public: true
    serial: true
    plan:
      - get: docker-goestools-src
        trigger: true
        passed: [build-and-publish-goestools]
      - put: docker-compose
        params:
            command: down
            compose_file: docker-goestools-src/docker/docker-compose.yml
      - put: docker-compose
        params:
            command: up
            compose_file: docker-goestools-src/docker/docker-compose.yml

    on_failure:
        try:
            put: hangouts-chat
            params:
                message: Failed to restart goestools BITCH Check that shit!

    on_success:
        try:
            put: hangouts-chat
            params:
                message: New goestools container restarted! bitch!
                post_url: false
