---
resource_types:
    - name: hangouts-resource
      type: docker-image
      source:
          repository: cloudinn/concourse-hangouts-resource
          tag: latest
          post_url: true

resources:
  - name: goestools-src
    type: git
    source:
      uri: https://github.com/pietern/goestools

  - name: docker-goestools-src
    type: git
    source:
      uri: https://github.com/hemna/docker-goestools

  - name: goestools-docker-image
    type: docker-image
    source:
        repository: 192.168.1.3:5000/hemna/goestools
        username: (( private-reg-user ))
        password: (( private-reg-password ))
        tag: latest
        debug: true
        insecure_registries: [ "192.168.1.3:5000" ]

  - name: hangouts-chat
    type: hangouts-resource
    source:
        webhook_url: (( hangouts-chat-webhook-url ))
        post_url: true

jobs:
  - name: build-and-publish-goestools
    public: true
    serial: true
    plan:
      - get: goestools-src
        trigger: true
      - get: docker-goestools-src
        trigger: true
      - put: goestools-docker-image
        params: 
          build: docker-goestools-src/build/

    on_failure:
        try:
            put: hangouts-chat
            params:
                message: Building the latest goestools docker image FUCKING FAILED BITCH!  HAHAHAH!!

    on_success:
        try:
            put: hangouts-chat
            params:
                message: New goestools image up bitch!
                post_url: false
